import { Stack } from '@mui/material';
import { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
const ClientStatusPage: NextPage & {
    layout?: string;
} = () => {
    const [caseView, setCase] = useState<'draft' | 'public'>();
    return (
        <Stack>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </Stack>
    );
};

ClientStatusPage.layout = 'client';
export default ClientStatusPage;
