import { Button, Stack, TextField, Typography } from '@mui/material';
import { NextPage } from 'next';
import Head from 'next/head';
import ApiCaller from '@/api';
import { useEffect, useState } from 'react';
const ContentSeriesPage: NextPage & {
    layout?: string;
} = () => {
    const [series, setSeries] = useState<any[]>([]);
    const [title, setTitle] = useState<string>('');
    const [summary, setSummary] = useState<string>('');
    useEffect(() => {
        ApiCaller.content.getAllSeries(0, 10).then((res) => setSeries(res.data));
    }, []);

    return (
        <Stack direction="row" sx={{ padding: '10px', gap: '10px' }}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Stack sx={{ gap: '10px', flex: 3 }} alignItems="center">
                <TextField
                    variant="outlined"
                    fullWidth
                    placeholder="Tiêu đề"
                    value={title}
                    onChange={(e) => setTitle(e.target.value)}
                />
                <TextField
                    variant="outlined"
                    multiline
                    rows={3}
                    fullWidth
                    placeholder="Mô tả"
                    value={summary}
                    onChange={(e) => setSummary(e.target.value)}
                />
                <Button sx={{ width: '40%' }} variant="outlined">
                    Create
                </Button>
            </Stack>

            <Stack sx={{ flex: 7 }}>
                <Stack direction="row" sx={{ gap: '10px', height: '100px' }}>
                    <Stack
                        sx={{
                            height: '100%',
                            aspectRatio: '1/1',
                            backgroundColor: '#B8A99A',
                            alignItems: 'center',
                            justifyContent: 'center',
                            borderRadius: '5px',
                        }}
                    >
                        <Typography>3</Typography>
                    </Stack>
                    <Stack>
                        <Stack>
                            <Typography sx={{ fontSize: '14px' }}>asdasdsa</Typography>
                        </Stack>
                        <Stack>
                            <Typography>
                                asdsads asd asd asdas asd asd asda as dasd asd asdasd asd asd asd a
                                sdas
                            </Typography>
                        </Stack>
                    </Stack>
                </Stack>
            </Stack>
        </Stack>
    );
};

ContentSeriesPage.layout = 'client';
export default ContentSeriesPage;
