import { NextPage } from "next";
import Head from "next/head";

const AuthPage: NextPage & {
  layout?: string;
} = () => {
  return (
    <div className="auth-page-root">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default AuthPage;
