import { Stack, Typography } from '@mui/material';
import { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import { TableContentComponent } from '@/components/table-content';
import { ClientStatusContent } from '@/components/client-status';
const ContentsPage: NextPage & {
    layout?: string;
} = () => {
    const [caseView, setCase] = useState<'draft' | 'public'>();
    return (
        <Stack>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Stack direction="row" sx={{ padding: '10px 20px' }}>
                <Stack
                    sx={{
                        overflow: 'hidden',
                        border: '1px solid black',
                        boxShadow: 'rgba(0, 0, 0, 0.24) 0px 3px 8px',
                        borderRadius: '5px',
                    }}
                >
                    <Stack>
                        <Typography
                            sx={{
                                fontSize: '14px',
                                fontWeight: 600,
                                cursor: 'pointer',
                                padding: '10px 20px',
                                transition: 'all ease .3s',
                                color: '#333',
                                '&:hover ': {
                                    backgroundColor: '#FFEBCC',
                                },
                            }}
                        >
                            Trạng thái
                        </Typography>
                    </Stack>
                    {/* ----- */}
                    <Stack>
                        <Typography>Bài viết</Typography>
                    </Stack>
                    <Stack>
                        <Stack
                            sx={{
                                paddingLeft: '20px',
                                '&:hover ': {
                                    backgroundColor: '#FFEBCC',
                                },
                            }}
                        >
                            <Typography
                                sx={{
                                    fontSize: '14px',
                                    fontWeight: 600,
                                    cursor: 'pointer',
                                    padding: '10px 20px',
                                    transition: 'all ease .3s',
                                    color: '#333',
                                }}
                            >
                                Công Khai
                            </Typography>
                        </Stack>
                        <Stack>
                            <Typography
                                sx={{
                                    fontSize: '14px',
                                    fontWeight: 600,
                                    cursor: 'pointer',
                                    padding: '10px 20px',
                                    transition: 'all ease .3s',
                                    color: '#333',
                                    '&:hover ': {
                                        backgroundColor: '#FFEBCC',
                                        color: '#333',
                                    },
                                }}
                            >
                                Bản nháp
                            </Typography>
                        </Stack>
                    </Stack>
                </Stack>

                <TableContentComponent />
            </Stack>
        </Stack>
    );
};

ContentsPage.layout = 'client';
export default ContentsPage;
