import { Stack } from "@mui/material";
import { NextPage } from "next";
import Head from "next/head";
import { TableContentComponent } from "@/components/table-content";

const ManagerContentPage: NextPage & {
  layout?: string;
} = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TableContentComponent />
    </div>
  );
};

ManagerContentPage.layout = "manager";
export default ManagerContentPage;
