import { Stack, TextField } from '@mui/material';
import Head from 'next/head';
import { HomeListContents, HomeTopContents } from '@/components/home-client';

const HomePage = () => {
    return (
        <Stack direction="row" sx={{ width: '100%' }}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <HomeListContents />
            <HomeTopContents />
        </Stack>
    );
};

HomePage.layout = 'client';
export default HomePage;
