import ApiCaller from '@/api';
import { ListContentInSeries } from '@/components/content-series';
import { CreateSeiresDialog } from '@/components/content-series/dialog';
import { Pagination, Stack } from '@mui/material';
import { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';

interface SeriesItem {
    contents: any[];
    created_at: string;
    summary: string;
    title: string;
    updated_at: string;
    _id: string;
}

const ContentSeriesPage: NextPage & {
    layout?: string;
} = () => {
    const [series, setSeries] = useState<SeriesItem[]>([]);

    console.log('series : ', series);

    useEffect(() => {
        ApiCaller.content.getAllSeries(0, 10).then((res) => setSeries(res.data));
    }, []);

    return (
        <Stack
            direction="column"
            sx={{ padding: '10px', gap: '20px', minHeight: '100vh' }}
            alignItems="center"
        >
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <ListContentInSeries series={series} />
            <Pagination
                onChange={(e, page) => {
                    console.log(page);
                }}
                count={20}
                defaultPage={1}
                siblingCount={1}
                variant="outlined"
            />
            <CreateSeiresDialog addSeries={(item: SeriesItem) => setSeries([...series, item])} />
        </Stack>
    );
};

ContentSeriesPage.layout = 'client';
export default ContentSeriesPage;
